import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/gallery.module.css'


export default function Gallery() {
  return (
    <div className='page-container'>
      <Head>
        <title>OrangeDigital</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        testing
        1
        2
        3
        4
        5
        6
        7
        8


      </main>

    </div>
  )
}
